Description:
    Jenkins CloudFormation template (EC2 instance).
  
Parameters:
  ProjectName:
    Description: ProjectName name, used as a prefix for resources
    Type: String

  WhiteListIP:
    Description: Whitelisted IP for SSH connection
    Type: String

  KeyPairJenkins:
    Description: KeyPair name to access Jenkins host via SSH
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: capstone

  ServerImageId:
    Description: Jenkins server image id
    Type: String
    Default: ami-0ac73f33a1888c64a # Ubuntu Server 18.04 LTS

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: HTTP and SSH access
      VpcId:
        Fn::ImportValue: !Sub "${ProjectName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub ${WhiteListIP}
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-JSG

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install default-jdk wget -y
          cd /home/ubuntu
          sudo wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
          sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
          /etc/apt/sources.list.d/jenkins.list'
          sudo apt-get update -y
          sudo apt-get install jenkins -y
          sudo systemctl start jenkins
          sudo systemctl enable jenkins
          sudo systemctl status jenkins
      SecurityGroupIds:
        - Ref: SecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub "${ProjectName}-SUBNET-1"
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "10"
            DeleteOnTermination: true
      ImageId: !Ref ServerImageId
      InstanceType: t3.small
      KeyName: !Sub ${KeyPairJenkins}

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Fn::ImportValue: !Sub "${ProjectName}-VPCID"

  EIPAssociation0:
    Type: AWS::EC2::EIPAssociation
    DependsOn:
      - Instance
      - EIP
    Properties:
      InstanceId:
        Ref: Instance
      AllocationId:
        Fn::GetAtt:
          - EIP
          - AllocationId

Outputs:
  Website:
    Description: EC2 instance DNS
    Value: !Join ['', ['http://', !GetAtt 'Instance.PublicDnsName', ':8080']]