---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone
  labels:
    app: devops-capstone
spec:
  selector:
    matchLabels:
      app: devops-capstone
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  minReadySeconds: 60
  progressDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: devops-capstone
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: devops-capstone
        image: maximilianschwab/devops_capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            scheme: HTTP
            port: 8080
          successThreshold: 1
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "service-devops-capstone"
spec:
  selector:
    app: devops-capstone
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080