apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::577034314422:role/capstone-project-kubernetes-node-NodeInstanceRole-17CPOQO01K3K4
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::577034314422:user/capstone_user
      username: capstone_user
      groups:
        - system:masters