AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon Kubernetes cluster'

Parameters:

  ProjectName:
    Description: Environment name, used as a prefix for resources
    Type: String

Resources:

  ClusterInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      RoleName: !Sub "${ProjectName}-KUBERNETES-CLUSTER-ROLE"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
  
  ClusterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref ClusterInstanceRole

  ClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Kubernetes Cluster security group
      GroupName: !Sub "${ProjectName}-KUBERNETES-CLUSTER-SEC-GROUP"
      VpcId:
        Fn::ImportValue: !Sub "${ProjectName}-VPC"
      Tags:
      - Key: !Sub "kubernetes.io/cluster/${ProjectName}-KUBERNETES-CLUSTER"
        Value: 'owned'
      - Key: 'Name'
        Value: !Sub "${ProjectName}-KUBERNETES-CLUSTER-SEC-GROUP"

  Cluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Sub "${ProjectName}-KUBERNETES-CLUSTER"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ClusterSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub "${ProjectName}-Subnet1"
          - Fn::ImportValue: !Sub "${ProjectName}-Subnet2"
          - Fn::ImportValue: !Sub "${ProjectName}-Subnet3"
      RoleArn: !GetAtt ClusterInstanceRole.Arn
      Version: 1.16

Outputs:

  ClusterSecurityGroup:
    Description: Control plane security group
    Value: !Ref ClusterSecurityGroup
    Export:
      Name: !Sub "${ProjectName}-KUBERNETES-CLUSTER-SEC-GROUP"
  
  Cluster:
    Description: Cluster name
    Value: !Ref Cluster
    Export:
      Name: !Sub "${ProjectName}-KUBERNETES-CLUSTER"